#Taken from https://docs.github.com/en/actions/guides/building-and-testing-nodejs-or-python
name: Typescript compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install oracle-server-ui dependencies
        run: |
         cd oracle-server-ui
         npm i
         tsc -p tsconfig.json
      - name: Install wallet-server-ui dependencies
        run: |
         cd wallet-server-ui
         npm i
         tsc -p tsconfig.json

